In [1]:
import numpy as np

In [2]:
set_w = np.array([[200]])
set_b = np.array([[100]])

In [3]:
x_train = np.array([[1.0], [2.0]], dtype=np.float32)

In [4]:
res = np.dot(x_train, set_w)

In [5]:
res

array([[200.],
       [400.]])

In [6]:
res2 = np.dot(set_w, set_b)

In [7]:
res2

array([[20000]])

In [8]:
Y_train = np.array([0,  0, 0, 1, 1, 1], dtype=np.float32).reshape(-1,1)  # 2-D Matrix
pos = Y_train == 1
pos

array([[False],
       [False],
       [False],
       [ True],
       [ True],
       [ True]])

In [9]:
X_train = np.array([0., 1, 2, 3, 4, 5], dtype=np.float32).reshape(-1,1)  # 2-D Matrix

In [10]:
X_train[pos]

array([3., 4., 5.], dtype=float32)

In [11]:
X_train[[True, False, False, False, True, True]]

array([[0.],
       [4.],
       [5.]], dtype=float32)

In [12]:
from tensorflow.keras.layers import Dense

In [13]:
from tensorflow.keras.models import Sequential

In [14]:
x = np.array([[200, 17]])

In [15]:
layer_1 = Dense(units=3, activation='sigmoid')

In [16]:
a1 = layer_1(x)

In [17]:
a1

<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1.1822347e-33, 4.5144865e-27, 5.3544661e-26]], dtype=float32)>

In [18]:
layer_1.get_weights()

[array([[-0.40766096, -0.2295739 , -0.21472174],
        [ 0.3361349 , -0.86751324, -0.8967608 ]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

In [19]:
layer_2 = Dense(units=1, activation='sigmoid')

In [20]:
a2 = layer_2(a1)

In [21]:
a2

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.5]], dtype=float32)>

In [22]:
x = np.array([[200, 17]])

layer_1 = Dense(units=3, activation='sigmoid', name='l1')
layer_2 = Dense(units=1, activation='sigmoid', name='l2')

# an alternative, simpler way of doing forward prop
model = Sequential([layer_1, layer_2])
res = model.predict(x)
res

1/1 [==============================] - 0s 186ms/step


array([[0.26429492]], dtype=float32)

In [23]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 l1 (Dense)                  (None, 3)                 9         
                                                                 
 l2 (Dense)                  (None, 1)                 4         
                                                                 
Total params: 13
Trainable params: 13
Non-trainable params: 0
_________________________________________________________________
